---
# Deploys a register from the store server

- name: Deploy Register
  hosts: store_server
  run_once: true
  tasks:
  - template:
      src: templates/pxelinux.cfg/register-{{ register_profile }}
      dest: /var/lib/tftpboot/pxelinux.cfg/{{ register_mac | regex_replace('\:', '-' ) }}
    
  vars:
    register_name: register1
    register_mac: 00:1a:4a:58:ec:93
    register_profile: rhel-server-7.6-x86_64

