---
# Redeploys a register from the store server
- name: Find register MAC
  hosts: "{{ register_name }}"
  tasks:
  - name: Gather facts for the register
    setup:
  
  - name: Set PXE config for register
    template:
      src: templates/pxelinux.cfg/register-{{ register_profile }}-deploy
      # This is the MAC address from the /register/ not from the delegated host.
      dest: /var/lib/tftpboot/pxelinux.cfg/01-{{ ansible_default_ipv4.macaddress | regex_replace('\:', '-' ) }}
    delegate_to: store_server

# TODO: We're rebooting regardless of whether or not we set the system to redeploy
  - name: restart server
    shell: sleep 2 && shutdown -r now "Redeployment"
    async: 1
    poll: 0
    ignore_errors: true
  
  - name: wait for server to come back
    local_action: wait_for host={{ register_name }} state=started delay=30 timeout=300
    sudo: false

  - name: Set PXE config for register
    template:
      src: templates/pxelinux.cfg/register-{{ register_profile }}
      # This is the MAC address from the /register/ not from the delegated host.
      dest: /var/lib/tftpboot/pxelinux.cfg/01-{{ ansible_default_ipv4.macaddress | regex_replace('\:', '-' ) }}
    delegate_to: store_server
  
  vars:
    register_name: register1
    register_profile: kiwi
